"""add test column

Revision ID: 8de396cf267b
Revises: 
Create Date: 2025-12-08 16:38:39.863463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8de396cf267b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latam_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'latam_docs', ['created_at'], unique=False)
    op.create_index('idx_document_type', 'latam_docs', ['document_type'], unique=False)
    op.create_index('idx_filename', 'latam_docs', ['filename'], unique=False)
    op.create_index(op.f('ix_latam_docs_filename'), 'latam_docs', ['filename'], unique=False)
    op.create_index(op.f('ix_latam_docs_id'), 'latam_docs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latam_docs_id'), table_name='latam_docs')
    op.drop_index(op.f('ix_latam_docs_filename'), table_name='latam_docs')
    op.drop_index('idx_filename', table_name='latam_docs')
    op.drop_index('idx_document_type', table_name='latam_docs')
    op.drop_index('idx_created_at', table_name='latam_docs')
    op.drop_table('latam_docs')
    # ### end Alembic commands ###
